M48
; DRILL file {KiCad (6.0.7)} date Thu Oct 20 09:09:37 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-20T09:09:37-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X106.25Y-58.75
X118.11Y-146.0
X193.75Y-58.75
X193.75Y-146.0
T0
M30
